# Generated by Django 3.2.4 on 2021-06-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('a_id', models.CharField(default='', max_length=64, primary_key=True, serialize=False)),
                ('a_pw', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('d_id', models.CharField(default='', max_length=64, primary_key=True, serialize=False)),
                ('d_name', models.CharField(default='', max_length=64)),
                ('d_telephone', models.CharField(default='', max_length=64)),
                ('d_hospital', models.CharField(default='', max_length=64)),
                ('d_department', models.CharField(default='', max_length=64)),
                ('d_pw', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='merchant',
            fields=[
                ('m_id', models.CharField(default='', max_length=64, primary_key=True, serialize=False)),
                ('m_name', models.CharField(default='', max_length=64)),
                ('m_telephone', models.CharField(default='', max_length=64)),
                ('m_pw', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('p_id', models.CharField(default='', max_length=64, primary_key=True, serialize=False)),
                ('p_name', models.CharField(default='', max_length=64)),
                ('p_telephone', models.CharField(default='', max_length=64)),
                ('p_pw', models.CharField(default='', max_length=40)),
            ],
        ),
    ]
