# Generated by Django 3.2.4 on 2021-06-09 15:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('r_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('r_hospital', models.CharField(default='', max_length=64)),
                ('r_department', models.CharField(default='', max_length=64)),
                ('r_time', models.DateField(default=datetime.date(1970, 1, 1))),
                ('d_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='identity.doctor')),
                ('p_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='identity.patient')),
            ],
        ),
        migrations.CreateModel(
            name='covid',
            fields=[
                ('c_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('c_type', models.IntegerField(default=0)),
                ('c_hospital', models.CharField(default='', max_length=64)),
                ('c_time', models.DateField(default=datetime.date(1970, 1, 1))),
                ('p_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='identity.patient')),
            ],
        ),
    ]
