# Generated by Django 3.2.4 on 2021-06-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('drug_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('drug_name', models.CharField(default='', max_length=64)),
                ('add_time', models.DateTimeField(auto_now=True)),
                ('drug_inventory', models.IntegerField(default=0)),
            ],
        ),
    ]
